# --- THIS IS THE CORRECT, SINGLE [project] SECTION ---
[project]
name = "binance-kedro-pipeline"
version = "0.18.14"
dependencies = [
    "kedro~=0.18.14",
    # FINAL FIX: Pin to a compatible version and use correct extras
    "kedro-datasets[pandas, pickle]~=2.0.0",
    "pandas==2.2.2",
    "numpy==1.26.4",
    "pyarrow",
    "scipy>=1.10.0",
    "numba>=0.57.0",
    "scikit-learn>=1.3.0",
    "lightgbm>=4.0.0",
    "river>=0.20.0",
    "ta>=0.11.0",
    "requests",
    "tqdm",
    "pandera==0.19.0",
    "pydantic>=2.0.0",
]
