version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - [%(levelname)s] %(message)s"
  rich:
    format: "%(message)s"
    datefmt: "[%X]"

handlers:
  # New handler for beautiful, live console logging
  rich_console:
    class: kedro.logging.RichHandler
    level: INFO
    formatter: rich
    rich_tracebacks: true
    show_path: false
    markup: true

  # New handler to save detailed logs to a file
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG # Log everything to the file
    formatter: simple
    filename: logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 3
    encoding: utf8
    mode: a

# The root logger captures all logs
root:
  level: DEBUG # Set root to DEBUG to capture everything for the file handler
  handlers: [rich_console, info_file_handler]

# Keep the Kedro framework logs at INFO to avoid excessive verbosity on the console
loggers:
  kedro:
    level: INFO
