version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rich:
    format: "%(message)s"
    datefmt: "[%X]"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console]

# Set the log level for the Kedro framework components
loggers:
  kedro:
    level: INFO
