labeling_params:
  # --- Method control and Fixed Percentage Barrier Parameters ---
  # Use 'fixed_pct' for fee-aware barriers or 'volatility' for the original dynamic method.
  method: "fixed_pct" 
  fee_pct: 0.00025             # 0.025% per trade

  # --- UPDATED: We now define the GROSS profit target ---
  profit_take_gross_pct: 0.0006 # Trigger when price moves up by 0.06% BEFORE fees
  stop_loss_gross_pct: 0.0001   # Trigger when price moves down by 0.02% BEFORE fees

  # --- Original Volatility-Based Parameters (can be used by setting method: 'volatility') ---
  vol_lookback: 50
  vol_multiplier: 2.0
  time_barrier_periods: 450
  profit_take_mult: 1.5
  stop_loss_mult: 1.5

lgbm_params:
  objective: 'multiclass'
  num_class: 3
  metric: 'multi_logloss'
  n_estimators: 250
  learning_rate: 0.03
  num_leaves: 20
  random_state: 42
  n_jobs: -1
  colsample_bytree: 0.7
  reg_alpha: 0.1
  reg_lambda: 0.1
  
