lgbm_params:
  # Improved hyperparameters for better performance and stability
  objective: 'multiclass'
  num_class: 3
  metric: 'multi_logloss'
  boosting_type: 'gbdt'
  n_estimators: 300           # was 250
  learning_rate: 0.025        # was 0.03 (slower for stability)
  num_leaves: 31              # was 20 (more expressive)
  max_depth: 8                # new (prevents overfitting)
  min_child_samples: 100      # new (reduces noise fitting)
  random_state: 42
  n_jobs: -1
  colsample_bytree: 0.7
  subsample: 0.8              # new (row subsampling)
  subsample_freq: 5           # new
  reg_alpha: 0.2              # was 0.1 (stronger L1)
  reg_lambda: 0.3             # was 0.1 
