
labeling_params:
  # --- NEW: Method control and Fixed Percentage Barrier Parameters ---
  # Use 'fixed_pct' for fee-aware barriers or 'volatility' for the original dynamic method.
  method: "fixed_pct" 
  fee_pct: 0.00025             # 0.025% per trade
  profit_take_net_pct: 0.0006  # Desired NET profit of 0.06%
  stop_loss_gross_pct: 0.0002  # GROSS price drop of 0.02% for stop-loss trigger

  # --- Original Volatility-Based Parameters (can be used by setting method: 'volatility') ---
  vol_lookback: 50
  vol_multiplier: 2.0
  time_barrier_periods: 30
  profit_take_mult: 1.5
  stop_loss_mult: 1.5

lgbm_params:
  objective: 'multiclass'
  num_class: 3
  metric: 'multi_logloss'
  n_estimators: 250
  learning_rate: 0.03
  num_leaves: 20
  random_state: 42
  n_jobs: -1
  colsample_bytree: 0.7
  reg_alpha: 0.1
  reg_lambda: 0.1
