
labeling_params:
  vol_lookback: 50
  vol_multiplier: 2.0
  time_barrier_periods: 30
  profit_take_mult: 1.5
  stop_loss_mult: 1.5

lgbm_params:
  objective: 'multiclass'
  num_class: 3
  metric: 'multi_logloss'
  n_estimators: 250
  learning_rate: 0.03
  num_leaves: 20
  random_state: 42
  n_jobs: -1
  colsample_bytree: 0.7
  reg_alpha: 0.1
  reg_lambda: 0.1
